pipeline {
    agent any
    
    options{
        buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
    }
    environment{
        PATH = "/usr/share/maven:$PATH"
    }
    
    parameters{
         gitParameter branchFilter: 'origin.*/(.*)', defaultValue: 'develop', name: 'BRANCH', type: 'PT_BRANCH'
    }
    
    stages {
        
        stage('Git Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                          branches: [[name: "${params.BRANCH}"]],
                          doGenerateSubmoduleConfigurations: false,
                          extensions: [],
                          gitTool: 'Default',
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: '5d366d73-5155-454f-b870-5de388d97287', 
                                               url: 'https://github.com/LHPH/kyc-core.git']]
                        ])
            }
        }
        
        stage('Build'){
            steps {
                sh "mvn clean install"
            }
        }

        stage('Deploy'){
            steps{
                sh "echo deploy in server"
            }
        }
    }
}