@Library('kyc-shared-library@master') _

deployAndroidApp(project: "kyc-mobile-android", credentials: '5d366d73-5155-454f-b870-5de388d97287',firebaseCredentials: 'fb5c7514-a47d-4c1c-a37c-a58d45c0a947');